[package]
name = "llamac_typed_ast"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
llamac_utils = { path = "../llamac_utils" }
llamac_ast = { path = "../llamac_ast" }
