[package]
name = "llamac_typecheck"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
llamac_utils = { path = "../llamac_utils" }
llamac_ast = { path = "../llamac_ast" }
llamac_typed_ast = { path = "../llamac_typed_ast" }
ariadne = "0.4"
