[package]
name = "llamac_sexpr_fmt"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
llamac_sexpr_fmt_derive = { path = "./llamac_sexpr_fmt_derive" }
