[package]
name = "llamac_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llamac_ast = { path = "../llamac_ast" }
logos = "0.12"
ariadne = "0.1"
